# Generated by Django 2.1.3 on 2018-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='actiontype',
            options={'verbose_name': 'Тип события', 'verbose_name_plural': 'Типы собитий'},
        ),
        migrations.AlterModelOptions(
            name='archcomplex',
            options={'verbose_name': 'Архитектурный комплекс', 'verbose_name_plural': 'Архитектурные комплексы'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
        migrations.AlterModelOptions(
            name='datatype',
            options={'verbose_name': 'Тип данных', 'verbose_name_plural': 'Типы данных'},
        ),
        migrations.AlterModelOptions(
            name='geomap',
            options={'verbose_name': 'Географическая карта', 'verbose_name_plural': 'Географические карты'},
        ),
        migrations.AlterModelOptions(
            name='historyaction',
            options={'verbose_name': 'Историческое событие', 'verbose_name_plural': 'Исторические события'},
        ),
        migrations.AlterModelOptions(
            name='historyevent',
            options={'verbose_name': 'Историческое событие', 'verbose_name_plural': 'Исторические события'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='leader',
            options={'verbose_name': 'Лидер', 'verbose_name_plural': 'Лидеры'},
        ),
        migrations.AlterModelOptions(
            name='mapobject',
            options={'verbose_name': 'Объект карты', 'verbose_name_plural': 'Объекты карты'},
        ),
        migrations.AlterModelOptions(
            name='mapobjecttype',
            options={'verbose_name': 'Тип объекта карты', 'verbose_name_plural': 'Типы объектов карты'},
        ),
        migrations.AlterModelOptions(
            name='maptype',
            options={'verbose_name': 'Тип  карты', 'verbose_name_plural': 'Типы  карт'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='modeltype',
            options={'verbose_name': 'Тип модели', 'verbose_name_plural': 'Типы моделей'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='photodownload',
            options={'verbose_name': 'Количество скачиваний', 'verbose_name_plural': 'Количество скачиваний'},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'verbose_name': 'Сцена', 'verbose_name_plural': 'Сцены'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='unithead',
            options={'verbose_name': 'Глава военного подразделения', 'verbose_name_plural': 'Главы военных подразделений'},
        ),
        migrations.AlterModelOptions(
            name='unittype',
            options={'verbose_name': 'Тип военного подразделения', 'verbose_name_plural': 'Типы военных подразделений'},
        ),
        migrations.AlterModelOptions(
            name='warunit',
            options={'verbose_name': 'Военное подразделение', 'verbose_name_plural': 'Военные подразделения'},
        ),
        migrations.AddField(
            model_name='archcomplex',
            name='name',
            field=models.TextField(default='None', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapobject',
            name='name',
            field=models.TextField(default='None', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scene',
            name='name',
            field=models.TextField(default='None', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Имя'),
        ),
    ]
